# permissions for end users to view relations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: relation-viewer-role
rules:
- apiGroups:
  - db.atlas.infoblox.com
  resources:
  - relations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db.atlas.infoblox.com
  resources:
  - relations/status
  verbs:
  - get
